# Configura칞칚o de integra칞칚o com Hugging Face
# Este arquivo configura a sincroniza칞칚o autom치tica entre GitHub e Hugging Face

# Nome do reposit칩rio no Hugging Face (ser치 criado)
repo_name: AIEXX/genai-image-to-3d

# Tipo de reposit칩rio no HF
repo_type: space  # ou 'model' dependendo do uso

# Branch padr칚o
default_branch: main

# Arquivos a serem sincronizados
include:
  - README.md
  - LICENSE
  - TODO.md
  - package.json
  - tools/**
  - workflows/**
  - exports/**

# Arquivos a serem exclu칤dos da sincroniza칞칚o
exclude:
  - .git/**
  - .venv*/**
  - node_modules/**
  - ComfyUI/**
  - "*.log"
  - .env*
  - .husky/**

# Metadados do Space/Model
metadata:
  title: "AIEXX GenAI Image to 3D"
  emoji: "游꿛"
  colorFrom: "blue"
  colorTo: "purple"
  sdk: "gradio"  # ou "streamlit" se preferir
  sdk_version: "4.0.0"
  app_file: "app.py"  # arquivo principal (a ser criado)
  pinned: false
  license: "mit"
  tags:
    - 3d-reconstruction
    - image-to-3d
    - zero123
    - triposr
    - instantmesh
    - controlnet
    - comfyui
    - generative-ai
    - stable-diffusion
    - computer-vision

